### ISSUE TITLE
Cloning for Litecoin Cloned Coin

### ISSUE THREAD

**Issue by phytocoin** [litecoin-association/LoafWallet#19]
Hello! Don't know if there is a way but I'm having some programmers try to use the loafwallet code to work with my litecoin clone. Since this coin is made for litecoin(scrypt) and my coin is a litecoin clone, shouldn't integration of my coin for loafwallet be easy? Thanks

**Comment by losh11** [comment]
What is your coin's PoW hash algorithm?
What coin is this? If I'm able to see the source code for this alt coin, I will be able to give a more accurate answer.

**Comment by phytocoin** [comment]
Hey Loshan T, 

Thanks for contacting me, you do great work with Loafwallet. 

Our coin's PoW is Scrypt and it hasn't been made public yet. Our website
is Phytocoin.org. There you can get the beta idea of what we are about.
We are trying to get everything at once before we launch such as getting
an exchange on our site, get listed on other exchanges, getting onto
coinpayments or Gourl.io, an android and ios wallet. I currently have
two different app companies trying to make us the ios and android wallet
but using your loafwallet source code as a starting point. Let's say
neither one of them can figure out how to make the wallets. It would be
a dissapointment to programmers everywhere, but let's say they can't.
Would you be interested in possibly making us the apps for our coin? We
would pay of course. I'm writing the whitepaper today for the coin so
that will take me some time but once it is finished I will email it to
you so you can look it over. We haven't published our source code for
the coin because of the nature of our coin. As you will see on our
website, our coin doesn't have any monetary value, it represents a range
of products and the ability to redeem the coins for those products.
Consider this an attempt to use cryptocurrencies for something other
than mining and making money off of the mining alone. Our coin has real
worth and its crucial we don't release the coin out to the public. If
working with us interests give me shout, you can email me here, my cell
is +1(417)316-3484 or my skype is dunnandcowan. My company has been
featured on Cointelegraph a few times and we just re-incorporated into a
new company so everything we do is by the book legal and compliant. 

Thanks, 

Joshua Dunn 

CEO  

>

**Comment by losh11** [comment]
Sent an email via the 'contact us' section of your website.

**Comment by phytocoin** [comment]
If you would please send the message again on our site as our SMTP 
settings were not correct I apologize. It's working fine now.

Joshua

**Comment by hendro123** [comment]
oke
